language: go
go:
- 1.8
script:
- go build -o liveness main.go
deploy:
  provider: bintray
  file: bintray.json
  user: serverhorror
  key:
    secure: 68W5hrXq6MOkrfovFxb76HEFM9KwhQybRYtpdc4OgkypXh2DfqmOpTK+KzpgFYIaPqzWb+anbZDo9tzZU93ZOnS/brUdPfOE50GnaGsrGJHyBWnxbO9NJa6jqekyYoFClUg4WxfZyUPrrZ4d8LLGDBsbMC5pMQFKuA4t7p0WA1/P+2AGNNgc+GsAfMN5/GCPlMFePa6J2cjxVEcSsJ27ufVFYtrArWmPTyDxnO22yyzZLoaXo30Q5bH4rNezF9bhgKS4P6L7zoZvMhWyJtbM6RlQ59ioWGOIORzda4GIySe5Jlc5A+RyAsIulMZ9P9/PABWn2nMCR59RSIsvZC5hC073WR4VJrI01ldGFdu+qKpPM68FjA00KHWdFDrpl15r0YgIWxsQNyJVUuHn9BXPQkZdQ4dZA4oOTQ/xE8J2Ta4ViksBL+SNhuffpNpvAaMejBlGGlyp2YjDAMll0ulb/GkusI6CYaY2+YIB0NZ9QDgrfASnsKiznJ1d+7QiGNqml1nDG96aY0Vbb80YfHa6FzKyanr76gu8XOhTsH94P5eiLEjfb/shOvk1+FseGaKKjCvgCPb1OzawL9KOJC0rDYXrqCaNUtXxli3hJW/rTQH4Gg4a78qJ4AjdfQnFipxSM2F8yJEPxO6o1rw2Brwa3LXAS6s5IxjLjMCZm2NNgJI=
