language: go
go:
  - 1.8
script:
  - go build -o liveness.${GOOS} main.go
env:
  - GOOS=linux
  - GOOS=windows
  - GOOS=darwin
before_deploy:
  - "zip liveness.zip liveness.*"
deploy:
  provider: releases
  file: "liveness.zip"
  api_key:
    secure: kxHnE3XDfNT8OkFOej4ZOoJXbhkbsKPyF8PDAgvcgrukxLoAEz5fQiwbbzRw3KHqysVwExeaY998q347meYL205Ta/Cbzx8I1gf8/G7ZwNRl9PNGJ+4c3fPNCRkeHJI0dNajGmIKv/PLl6rlDeV8ExWr9uF19MfSNbVvsUczvaa5asCCGHrVW8KAqhGpLQdQGkGApovTr6d+d2rXuGFPWiAiDXDxHIeTWOvMoyG7HUXpUE2GokCmxM/AijG1YQSlGSafIdkM67GWfC6CSbLkf0iBTfBQXCZbL7c2C/VFp+5n4crUJbgn7jN+ywMLpEVi8heQRa5bR/vsxUmzTtmgEfJTICn+U606Gbf5U+OvhWgDulx6azxb0luBqcUjt2fYultNja3t7mPESApvOVL71vwebMM3XNqR0AIUyJQ8mBixCNvkxOodh6y4961EX5keJSA7vtrk7BNXWC9+I7A3hWPf394PC0kweEQgT/O7CxBaWUYq5rDsBCueyJzu0tObJthXBJgeKOl6skt6gRHyggcPZnyfE2vCbiC2mRTygwuseqwMJvdOzLDl0o5bk3oKjSc0PydILwKRd/nMSJnC79XZ22kRiZpgb5UjiPyhhkKd9ty03O1dg/SG8BWpKbPyRYzQUmas9b6F8DYx78MhRxvwQirpZ2Un2OsC5UctNdM=
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
after_deploy:
  - "unzip -l liveness.zip"
